### ISSUE TITLE
슬라이드 인터페이스개선

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#1]
우선 잘 움직이지도 않고 이상하게 작동함.
그리고 여러 패턴때문에 정확히 겹치는 형태를 갖게 되기 때문에 불편함.
![image](https://user-images.githubusercontent.com/5790535/117404787-842bcf80-af45-11eb-89da-77877d1d508c.png)

차라리 각 레이어에 게이지와 숫자인풋으로 정확히 위치를 표시해주고 
최상단에는 그것의 결과물만 보여주는게 나을듯.

**Comment by redcamel** [comment]
@hikaMaeng 처리완
