### ISSUE TITLE
컬러게이지를 아래로 옮긴 경우 미리보기

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#10]
![image](https://user-images.githubusercontent.com/5790535/117416522-6b76e600-af54-11eb-8129-caa2a168025f.png)
위에는 차라리 각레이어별 색상이 어떤 레인지에서 생겨났는지 알기쉽게 표현되는게 나을듯.

**Comment by redcamel** [comment]
@hikaMaeng 
![image](https://user-images.githubusercontent.com/820587/117426572-ff4daf80-af5e-11eb-850f-1305e9fdd41c.png)
이개념 나쁘지 않네용

**Comment by hikaMaeng** [comment]
ㅇㅇ
오 완전 맘에 들게 되었다 굳

**Comment by hikaMaeng** [comment]
이제 컬러레이어 두개 묶어서 자물쇠걸어두는 기능만 만들면 ㅋㅋ
아니 처음부터 듀얼타입으로 체크 박스 만들자
![image](https://user-images.githubusercontent.com/5790535/117435975-67a18e80-af69-11eb-9d5f-4b5a706c2fd2.png)

**Comment by redcamel** [comment]
듀얼이란건....
미묘한 간극이 귀찮으니....
한방에 처리한다는 의미인가요?

**Comment by hikaMaeng** [comment]
맞아. 굳이 내가 그 노가다를 컬러레이어 두개를 만들어서 할 이유가 있나

2021년 5월 8일 (토) 오후 6:18, Redcamel ***@***.***>님이 작성:
