### ISSUE TITLE
포지션, 사이즈가 %모드일때 계산정리해내야함

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGradient#101]
![image](https://user-images.githubusercontent.com/820587/119844678-9943bf00-bf43-11eb-8667-9dc5a7d17fcc.png)

**Comment by redcamel** [comment]
흠 이거 어렵넹

**Comment by hikaMaeng** [comment]
아 그거말고도
![image](https://user-images.githubusercontent.com/5790535/119922803-8bc21f80-bfab-11eb-963c-aa8066873919.png)
상하좌우 크기 조절점도 아무래도 추가해야겠음.
무조건 상하좌우가 동시에 변하니까 가로로만 넓히거나 세로로만 넓히기가 너무 어려움
