### ISSUE TITLE
2단레이어레이아웃을 3단으로 변경하는게 나을듯

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#102]
![image](https://user-images.githubusercontent.com/5790535/119949139-8a591d00-bfd4-11eb-9d69-4e1ed8d28909.png)
불편함.
차라리 그라데이션 내부의 윗부분과 아래 컬러레이어를 단으로 나눠서 3단구성이 되게 하는게 좋을듯
특히 비주얼에디터 오면서 마우스질한걸 수치로 보면서 하는게 좋은데
컬러레이어도 많아지면서 스크롤이 귀찮게 굼

**Comment by redcamel** [comment]
음
