### ISSUE TITLE
사이즈 조절기에 비율묶기 기능 추가

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#110]
![image](https://user-images.githubusercontent.com/5790535/120146004-62112e80-c21f-11eb-9893-88828e152cdd.png)
누르는 순간부터 묶이고 비주얼에디터에도 영향을 주도록

**Comment by redcamel** [comment]
리사이즈시 쉬프트 정사이즈 고정도 추가

**Comment by hikaMaeng** [comment]
쉬프트 최고!

2021년 6월 1일 (화) 오전 2:24, Redcamel ***@***.***>님이 작성:

**Comment by redcamel** [comment]
resolved
