### ISSUE TITLE
컬러레이어도 이동가능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#114]
![image](https://user-images.githubusercontent.com/5790535/120257462-44999e80-c2cb-11eb-9520-41cbad88c0a1.png)

컬러레이어도 이동할 일이 많은데 안되서 삽질 엄청함

**Comment by redcamel** [comment]
음 지금 오토 소팅을 하고있는디 옵션으로 풀어야것네용

**Comment by hikaMaeng** [comment]
아무래도 오토보다는 레인지값이 틀려도 색상배치를 커스텀으로 한뒤 다시 레인지를 맞추는 식으로 작업하는 경우가 많은듯

2021년 6월 3일 (목) 오전 4:13, Redcamel ***@***.***>님이 작성:

**Comment by redcamel** [comment]
@redcamel @hikaMaeng 
[x] 기본오토소팅은 해제
[x] 레이어 드래그 드롭 지원
[x] 오토소팅 버튼 지원
![image](https://user-images.githubusercontent.com/820587/128661695-7f6bd3bf-b624-4b9f-89c8-126eaf0f24c9.png)
