### ISSUE TITLE
그라데이션레이어 이동시 진동문제 해결

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#115]
![image](https://user-images.githubusercontent.com/5790535/120257556-6b57d500-c2cb-11eb-9a45-ca8d7c482c73.png)

아주 두 레이어가 번쩍거리면서 지랄을 함.. 진동을 잡으라능

**Comment by redcamel** [comment]
resolved

**Comment by hikaMaeng** [comment]
아니 이렇게 이쁘게 해결할거면서 그렇게 두었다니..=.=

2021년 6월 3일 (목) 오전 12:27, Redcamel ***@***.***>님이 작성:
