### ISSUE TITLE
첫화면 너무 거슬림

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#117]
![image](https://user-images.githubusercontent.com/5790535/120258518-2c2a8380-c2cd-11eb-8581-3ed89b64ffb8.png)
중앙이미지가 늦게 로딩되면서 밀려나는거 매번 보기 괴로움
base64로 직접 박아버리던가 로고로딩후에 화면나오게 하던가..
서비스 워커로 캐쉬를 잡아두던가 로컬스토리지에 박아두던가 뭐라도 하라능..

**Comment by redcamel** [comment]
resolved
