### ISSUE TITLE
레이어별 사이즈 정책에 대해

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#12]
음 레이어별 사이즈 정책을 안가져가고 캔버스 사이즈만 가져가는 정책정도에서 멈추는게 어떻까.
하나의 div용 css background 속성 하나만 점유하게..
너무 html구조나 js보조까지 포함지 않는 background css생성기에서 벗어나지 않는 기조가 딱 좋은데...

**Comment by hikaMaeng** [comment]
안그러면 금새 윅스같은 종합 개발툴이 되어버림

**Comment by redcamel** [comment]
음 이게.... #9 과 연관된건데..
- 레이어로 그라데이션 영역 사이즈자체를 결정하고...
- 레이어내의 그라데이션들의 스텝은 퍼센트 모델로 결정
이방식으로 오늘 변경한건데...
좀더 개념정리후 결정해보는걸로

**Comment by hikaMaeng** [comment]
근데 그러면 실 출력은 html구조물과 같이 export하게 됨.
난 애니메이션까지도 시간을 정하면 그 시간에 맞게 적당히 슬라이스해 키프레임애니메이션으로 번역해
완전히 출력이 하나의 div용 순수 css만 떨어져나오면 좋겠음. 그래야 의존성 없이 사방에서 쓸 수 있음

**Comment by hikaMaeng** [comment]
툴 사정이나 짜고 싶은 알고리즘 기준으로 구현하면 툴에는 기능이 구현되지만 실제 프로젝트에 적용할때는 툴의 규칙대로 html과 js를 써야하기 때문에 실무에 적용하기가 점점 어려워짐

**Comment by redcamel** [comment]
ㅇㅇ 의도하는 결과물은 단일 css 클래스 덩어리 하나여용

**Comment by hikaMaeng** [comment]
음 그럼 저 사이즈를 나중에는 다 캔버스 사이즈로 번역해서 하나로 합쳐주는 개념인가..
200짜리라 100짜리가 있으면 좌상단으로 정렬되는건가..
아니 그리고 짜피 그렇게 하나의 div배경이 될거면 시작 위치만 의미가 있지 width, height의 의미가 있나..

**Comment by redcamel** [comment]
#9 로병합
