### ISSUE TITLE
조절점은 확대해도 원래 크기를 유지하게

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#120]
![image](https://user-images.githubusercontent.com/5790535/120330849-2f069200-c328-11eb-8f98-3abea5388056.png)
줌하다가 조절점으로 화면 채울 기세

**Comment by redcamel** [comment]
resolved

**Comment by hikaMaeng** [comment]
우와! 완벽 너무 좋음. 이거 뭔가 이 변화로 진짜 상용제품같은 느낌이 확나네..
새삼 이게 그렇게 아마츄어틱하게 거슬렸던 부분이었나봐

2021년 6월 2일 (수) 오후 1:25, Redcamel ***@***.***>님이 작성:
