### ISSUE TITLE
result패널이 스크롤바를 만들어내지 않음

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#121]
![image](https://user-images.githubusercontent.com/5790535/120330955-45ace900-c328-11eb-8af2-7a849d533b8a.png)
스크롤바가 생기지 않음

그에 비해 위에 포지션까지는 브라우저를 줄였을때 정상적으로 스크롤바 생성
![image](https://user-images.githubusercontent.com/5790535/120331033-55c4c880-c328-11eb-9c20-dc9086c26b3d.png)

**Comment by redcamel** [comment]
resolved
