### ISSUE TITLE
반시계 방향 회전시 버그

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#122]
![image](https://user-images.githubusercontent.com/5790535/120568339-a0406500-c44e-11eb-9e80-fdc0d9458651.png)

반시계방향으로 회전시켜보면 한 45도 이후엔 오히려 반대방향으로 회전하는걸 볼 수 있음..
뭔가 회전계산하는게 잘못된듯

**Comment by hikaMaeng** [comment]
아니 이거 시계방향도 마찬가지인걸?

**Comment by redcamel** [comment]
이게 회전시각시 가상 시작점을잡고 한번더 각도처리를해주면해결될듯

**Comment by redcamel** [comment]
resolved

**Comment by redcamel** [comment]
흠 쉽게 고쳤더니...또다시 감도가 민감해지는군요 -0-
두개를 조합해서 재 처리하는걸로

**Comment by redcamel** [comment]
방향은 고쳐졌으나 초기 값 표시에 대해서 좀더 부드럽게 표현할 방법 연구해야함

**Comment by redcamel** [comment]
@hikaMaeng #149 로 변경 처리완
![image](https://user-images.githubusercontent.com/820587/130391531-30bef5a6-49de-4d5c-9840-b7a1eabb7fec.png)
