### ISSUE TITLE
익스포트 카피 얼럿 제거

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#124]
![image](https://user-images.githubusercontent.com/5790535/120572791-89524080-c457-11eb-9324-f7de00b6d7e2.png)
얼럿정도로 심각한 일이 아니므로 얼럿을 제거하고 대신
토스트(살짝 보였다가 자동으로 사라지는 안내창)으로 대체

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/120586490-99294f00-c46e-11eb-996f-25189cdbc2ea.png)
토스트 일단 도입했고...
위치나 디자인 경험은 보강하는걸로
