### ISSUE TITLE
창닫기 방지 개선

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#125]
![image](https://user-images.githubusercontent.com/5790535/120572879-ae46b380-c457-11eb-8592-2c0c61e2fcb6.png)
현재 무조건적으로 뜨고 있는 이 알럿..

세이브 이후 어떠한 인터렉션도 없었다면 그냥 닫을 수 있게..

**Comment by redcamel** [comment]
@hikaMaeng 세이브, 로드시 창안뜨게 개선
