### ISSUE TITLE
컨테이너 프로퍼티는 접을 수 있게

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#127]
![image](https://user-images.githubusercontent.com/5790535/120603323-dd284e00-c486-11eb-966a-f1b27059acda.png)
왼쪽으로 접을 수 있게 하고
접은 상태는 로컬스토리지로 기억

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/120612664-63955d80-c490-11eb-8af1-255ed33897e5.png)
이느낌인겐가요

**Comment by hikaMaeng** [comment]
미래를 생각하면 그렇지. 지금 당장은 그것만 접히는 것으로도 충분하지만

2021년 6월 3일 (목) 오후 5:23, Redcamel ***@***.***>님이 작성:

**Comment by redcamel** [comment]
resovled
