### ISSUE TITLE
템플릿 생성버그

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#128]
![image](https://user-images.githubusercontent.com/5790535/120606738-7ad14c80-c48a-11eb-8f68-fb17cb0f5ab0.png)
야 뭔가 스타트 엔드가 반대로 생성된거 같지 않냐..

**Comment by redcamel** [comment]
음 일단
템플릿 생성시...  deg는 나올수는 없는디...
상황발생이 가능할지 확인좀 해볼꼐요
