### ISSUE TITLE
컬러레이어 스크롤 불편개선

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#14]
![image](https://user-images.githubusercontent.com/5790535/117436187-ab949380-af69-11eb-88f8-d8d3b943e548.png)
저 부분은 FIXED로 해줘

**Comment by redcamel** [comment]
@hikaMaeng 처리완

**Comment by hikaMaeng** [comment]
아니 아직 fixed안되고 같이 스크롤되는데?
![image](https://user-images.githubusercontent.com/5790535/117560824-16f67680-b0cc-11eb-9a8e-df171ed2948b.png)
