### ISSUE TITLE
ui개편

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#140]
![image](https://user-images.githubusercontent.com/5790535/123187039-54745f00-d4d4-11eb-8f13-4663fef5142f.png)
그라데이션 배경처리기는 결국 속성중에 일부인 것

**Comment by hikaMaeng** [comment]
그리고 저 캔버스의 조절점 자체도 그라데이션 탭을 고를때만 나오게하고
컨테이너 속성의 width, height등 각 탭별 필요한 조절점이 따로따로 나오게 개편

**Comment by redcamel** [comment]
resolved
