### ISSUE TITLE
버그..

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#142]
![image](https://user-images.githubusercontent.com/5790535/123889781-24740280-d991-11eb-9338-a83ac788c78a.png)
템플릿 추가시 +버튼을 누르면 갑자기 무한 증식함

**Comment by redcamel** [comment]
@hikaMaeng resolved

@redcamel RedNumber객체에서 컨텍스트문제로 발생됨...
일단 복제처리로 떔빵하였으나...
본질적으로 수정해야함
