### ISSUE TITLE
커스텀 css가 반영되지 않음

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#143]
![image](https://user-images.githubusercontent.com/5790535/123891540-0956c200-d994-11eb-81d9-220abfd0a9ca.png)
나 뭔가 잘못쓰고 있나?

**Comment by redcamel** [comment]
```-webkit-mask-image``` or ```-webkit-mask```
```-webkit-mask-image :radial-gradient(transparent 0.5%, red 100%)```
단위도 px나 %처럼 명시적으로 작성하면되네요
