### ISSUE TITLE
현재 REPEAT와 레이어사이즈의 문제

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#19]
![image](https://user-images.githubusercontent.com/5790535/117564706-5763ed80-b0e8-11eb-9ff1-3b9e7bf4d18b.png)
이 형태처럼 반복시 공간을 띄우는 형태의 반복을 만들 수 없음 이 구조로는..

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/117564729-71053500-b0e8-11eb-8e78-fe2a81020950.png)

**Comment by hikaMaeng** [comment]
여유 공간을 갖고 반복되는 패턴을 만들 수 없다능.

**Comment by redcamel** [comment]
@hikaMaeng 
- 레이어 사이즈 삭제
- 그라디언트 사이즈 부활
- 그라디언트 스텝 단위 변환 부활
![image](https://user-images.githubusercontent.com/820587/117610571-f0ecd700-b19c-11eb-93a9-397c9fe8b3a8.png)
