### ISSUE TITLE
레어이안의 각 그라디언트 순서 조정가능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#2]
![image](https://user-images.githubusercontent.com/5790535/117404965-d4a32d00-af45-11eb-97a7-0862d02accdc.png)
얘들 드래그로도 가능하고 위아래버튼으로도 이동가능하게 만들어주라능

**Comment by redcamel** [comment]
드래그드랍으로 해결볼 생각이여요~

**Comment by redcamel** [comment]
@hikaMaeng 동작은 처리완
