### ISSUE TITLE
undo, redo 처리

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGradient#27]
undo, redo 처리

**Comment by hikaMaeng** [comment]
어렵게 구현하려고 하지말고 짜피 현재 상태를 저장할 수 있게 직렬화가 되니까
액션이 일어날때마다 직렬화 상태를 메모리에 적당한 단계까지 저장하고 그걸로 LOAD해주면 될듯

**Comment by redcamel** [comment]
짜피이겆최상위스테이트물고있으면되서 걍먹을듯

**Comment by redcamel** [comment]
일단 굴러감
