### ISSUE TITLE
range좀더 연구

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGradient#28]
range좀더 연구

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/118068584-92fb0200-b3dd-11eb-91c5-8342e269131e.png)
한참 갖고 놀아본 결과 매우 만족스러움
일단 레이어간 게이지 제약은 오히려 없는게 편한듯
즉 위 레이어가 0~20%라 할지라도 아래 레이어가 15%~30%로 설정할 수 있는게 더 편함 이대로 유지하면 될듯

단 두가지는 고쳐봐야할듯


1. s포인트가 e포인트랑 위치가 역전되면 자동으로 s, e가 바뀌는 기능 추가
2. 레인지를 선택하면 자동으로 입력폼이 두개로 변경되는 기능 추가

**Comment by redcamel** [comment]
@hikaMaeng 처리완
