### ISSUE TITLE
무성의한 아이콘 치우고 제대로 파비콘 만들기

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#30]
![image](https://user-images.githubusercontent.com/5790535/118092021-817a2000-b406-11eb-8a73-f36bcb8a2e03.png)
리액트앱 기본 아이콘 치우고 좋은 아이콘 만들어 올리라능. 없어보임.
그리고 애드센스 게으름 피지말고 빨리 달아

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/118215717-0c155a80-b4ad-11eb-895b-994c4cfaecf3.png)
음 아니야..흰배경 페북처럼 제대로 빼주라능

**Comment by redcamel** [comment]
#54 로통합
