### ISSUE TITLE
Preview 개념잡기

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGradient#33]
Preview 개념잡기
단순 프리뷰보다는 실제 사이트에...
드래그 드랍으로 위치시켜보는 정도가 되면 좋을듯한데...

**Comment by hikaMaeng** [comment]
아니 그건 필요없을듯..괜히 목적에서만 벗어남..오히려 하고 싶다면 배경이미지 업로드를 하는건 나쁘지 않음.
개념상으로보면
![image](https://user-images.githubusercontent.com/5790535/118214458-b2ac2c00-b4aa-11eb-801d-4270db322d01.png)
이런건데
배경을 줌인아웃하고 드래그해서 위치를 이동시킬 수 있으면 되는듯
배경은 iframe을 포함하면 다른 사이트도 가능하고 기본은 업로드한 이미지

**Comment by easylogic** [comment]
iframe 은 cors 문제 때문에 다른 도메인을 바로 못 불러 올 수도 있어요.

**Comment by hikaMaeng** [comment]
그거야 중계서버거치면 그만이지

2021년 5월 14일 (금) 오후 12:38, jinho park ***@***.***>님이 작성:

**Comment by hikaMaeng** [comment]
그러고보니 선기의 답변이 아니라 진호님의 답변이었군요 ㅋㅋㅋㅋ

**Comment by redcamel** [comment]
추후고민모드로...전환 이슈 닫음
