### ISSUE TITLE
리버스버튼 신설

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#34]
![image](https://user-images.githubusercontent.com/5790535/118210438-71654d80-b4a5-11eb-869c-b2ff8b7b8b59.png)
이자리쯤에 reverse버튼 신설하고
누르면 그라데이션을 반대방향으로 바꿔주게해줘 포샵처럼

**Comment by redcamel** [comment]
굴러는가는데... 완벽하진 않을듯요
