### ISSUE TITLE
레이어 추가 정보가 이상한 위치에 있음

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#4]
![image](https://user-images.githubusercontent.com/5790535/117413308-c73f7000-af50-11eb-8c98-3b91d42efb5e.png)
이것도 우측 색상처리기 위쪽이라던가 제대로된 위치로 이동
![image](https://user-images.githubusercontent.com/5790535/117413385-de7e5d80-af50-11eb-8975-3c11acb3b42b.png)

**Comment by redcamel** [comment]
@hikaMaeng 처리완

**Comment by hikaMaeng** [comment]
이거하면서 스크롤 fixed했던거 깨진거 아니냥

2021년 5월 8일 (토) 오후 6:14, Redcamel ***@***.***>님이 작성:
