### ISSUE TITLE
하단 사이즈 관련된걸 전부 사이즈쪽으로

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#41]
![image](https://user-images.githubusercontent.com/5790535/118213817-99ef4680-b4a9-11eb-8c1a-bff8534de81e.png)
이거 결국 왼쪽 사이즈 설정쪽으로 와야함. 괜히 여기 있을 필요가 없음 눈에만 안띄고..
나중에 이자리도 애드센스 자리임

**Comment by redcamel** [comment]
#42 로 병합
