### ISSUE TITLE
프리셋 추가삭제기능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#43]
![image](https://user-images.githubusercontent.com/5790535/118214723-3fef8080-b4ab-11eb-8b75-a480dce404ac.png)
이쯤에 현재 그라데이션을 프리셋에 추가하는 버튼을 달아줄것
그리고 시스템이 기본제공하는 프리셋은 삭제가 안되지만
그리고 LOAD, SAVE할때 유저프리셋도 포함할것

**Comment by hikaMaeng** [comment]
아니 이게 프리셋이니 다른 프로젝트에서도 써야하니까..
로컬스토리지에 저장하는게 낫겠다.

**Comment by hikaMaeng** [comment]
니가 컨텍스트별로 프리셋이 다르게 나오듯, 저장도 컨텍스트별로 이쁘게 되게 하라능

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/118216228-18e67e00-b4ae-11eb-9807-4876eafaa820.png)
프리셋 이름은 여기서 가져오면 되겠다
이 이름 완전 쓸모없었는데 유일한 쓸모를 찾았음

**Comment by redcamel** [comment]
@hikaMaeng 처리완
![Uploading image.png…]()

**Comment by redcamel** [comment]
음... 익스포트와 임포트도 필요하것군요

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/118364118-0bc2af80-b5d2-11eb-85ad-39ac0675670d.png)
처리완
