### ISSUE TITLE
캔버스 드래그 이동기능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#44]
![image](https://user-images.githubusercontent.com/5790535/118216097-cf962e80-b4ad-11eb-98d5-072833470650.png)
이게 휠로 줌인아웃은 잘되는데 이동이 안되서 불편함 드래그로 이동할 수 있게 변경
나중에 배경들어오면 더 필요해지기도 하고

**Comment by redcamel** [comment]
쉬프트도 필요없는듯요...
그냥 드래그하면 이동되는형식으로 처리
