### ISSUE TITLE
레이어 접기 기능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#45]
![image](https://user-images.githubusercontent.com/5790535/118216898-50a1f580-b4af-11eb-85ce-28ef5e6dca4b.png)
접으면 소속 컬러레이어는 안보이게

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/118364540-c4d5b980-b5d3-11eb-8d03-3ecce25c0668.png)
원래 접기 영역이 저빨간영역이였는데
영역을 확장시키는선으로 마무리
