### ISSUE TITLE
캔버스 편집기에 border 그라데이션은 어쩔것인가

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#47]
https://zinee-world.tistory.com/453

보더에 그라데이션이랑 백그라운드 그라데이션이 섞으면 재밌는 효과가 많이 일어남 특히 보더 radius랑 섞어서 많은걸 만들 수 있지

**Comment by redcamel** [comment]
디테일한 수정은 개별 이슈화로 처리
