### ISSUE TITLE
결과창 선택안됨..

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#58]
![image](https://user-images.githubusercontent.com/5790535/118478655-1c4a6580-b74b-11eb-9f4d-70e8b39ebff2.png)

미친...선택되게 해달라..

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/118527556-61d35680-b77c-11eb-929f-2a2385989fff.png)
