### ISSUE TITLE
ui전반적으로 애니메이션을 고려할 것

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#6]
결국 애니메이션을 고려해보면 
1. 각 그라데이션 레이어별로 - 레이어별(회전, 중앙x,y, 반복)
2. 각 색상별로 색상, 위치
3. 에 대해 애니메이션이 일어나는게 기본임

지금은 js트위닝으로만 해야하니까 결국 레이어가 키프레임을 설정해서 각 레이어별 속성인 회전 중앙x,y반복  및 색상별 변화에 대해 시작과 끝을 지정할 수 있는 형태여야함.
그렇게 생각하면 지금 너무 방만하게 화면을 쓰고 있는 느낌도 있음.
키프레임별로 이 셋트를 계속 늘려갈 수 있게 해주면 좋겠음.

![image](https://user-images.githubusercontent.com/5790535/117414238-df63bf00-af51-11eb-8d35-d34c6b39c99b.png)

개념적으로보면 이렇게 키프레임별로 이 셋트가 다 들어가야 예상되는 애니메이션을 작성할 수 있을 것임

**Comment by redcamel** [comment]
#55 로통합
