### ISSUE TITLE
사이트GNB디자인

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#62]
![image](https://user-images.githubusercontent.com/5790535/118623718-7d357480-b803-11eb-995a-cef7cd44d239.png)
먼가 로고파트 말고도
GNB배경에 이게 그라데이션 툴이라는걸 알려줄 수 있게 뭔가 넣었으면 좋겠다

**Comment by redcamel** [comment]
#126 번으로 통합
