### ISSUE TITLE
+버그

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#64]
![image](https://user-images.githubusercontent.com/5790535/118624562-3a27d100-b804-11eb-93b3-26990f1e30c8.png)
뭔가 어떤 순간부터 젤 마지막+가 작동안하게 되는 버그가 있음

레인지를 막 누르다가 작업하다가 뭐하다보면
마지막 컬러레이어만 +가 안됨

**Comment by redcamel** [comment]
저버튼과 아래 컨테이너 버튼이벤트 위계가 애매하게 겹쳐있었네용...
처리완~
