### ISSUE TITLE
보더프리셋 익스포트 확장자가 변태

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#65]
![image](https://user-images.githubusercontent.com/5790535/118625374-ebc70200-b804-11eb-96d2-0d230d6bb8ee.png)
걍 얌전히 이넘도 확장자는 json으로..
그리고 짜피 보더익스포트도 배경 임포트랑 호환되는데...굳이..=.=

**Comment by redcamel** [comment]
안되는줄 알고 구분 해둔건데..
가만생각해보니 같은 에디터에 데이터만 부르는거라 가능하다는 -0-;;;;
밤에 풀어둘꼐요...~

**Comment by redcamel** [comment]
처리완
