### ISSUE TITLE
각도입력기

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#7]
![image](https://user-images.githubusercontent.com/5790535/117414863-99f3c180-af52-11eb-9e5a-066c59e296d7.png)
회전과 관련된 ui가 불편

![image](https://user-images.githubusercontent.com/5790535/117415333-27371600-af53-11eb-8cc6-16feb8d6fa26.png)
이런식으로 지정한 각도를 보기 쉽고 편집하기 쉽게..텍스트창도 지원하고 동그라미 돌려도 되게..

**Comment by redcamel** [comment]
@hikaMaeng 처리완

**Comment by hikaMaeng** [comment]
배리굿 근데 이거 이메일로 답해도 이슈에 답이 되나..

2021년 5월 8일 (토) 오후 6:13, Redcamel ***@***.***>님이 작성:

**Comment by hikaMaeng** [comment]
음 이메일로 답하면 답이 안되는군. 베리굿생각보다 더 잘나왔음

**Comment by hikaMaeng** [comment]
어..딜레이가 있지만 이메일로 답해도 되는구나..
