### ISSUE TITLE
애니메이션 전까지 어느정도 마감되면 버전릴리스 하라능

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#70]
적절할 때 0.1.0 로 태그달아서 릴리즈하라능

릴리즈할때 기능리스트업 잘하고
이게 베이스 버전일테니까

이후 핫픽스는 0.0.xxx를 사용하고
애니메이션 전까지는 기능이 어느정도 갖출때마다 0.xxx.0 을 사용하고
1.xxx는 애니메이션이 도입되었을때
2.xxx는 그 이후에 생각해보장

버전릴리즈는 커뮤니케이션을 위해서라도 기본셋이 만들어지면 빨리빨리 해야함 
안그러면 엔드리스 개발을 하게 됨

**Comment by redcamel** [comment]
주중에 베타 릴리즈하는걸로
