### ISSUE TITLE
컬러레이어복사버그

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#72]
![image](https://user-images.githubusercontent.com/5790535/118950751-70488a80-b995-11eb-865f-5801b0350d63.png)
레인지를 설정한 레이어의 +를 누른경우
레인지에 체크가 되었지만 실제로는 레인지가 아닌 상태로 새로운 레이어가 생성됨

**Comment by redcamel** [comment]
처리완
