### ISSUE TITLE
자동레이어 생성기능 고찰

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#73]
![image](https://user-images.githubusercontent.com/5790535/118951146-cf0e0400-b995-11eb-9fc2-e138e0b84dca.png)
이런식으로 일정 범위를 갖거나 이징함수를 통해서 일정 간격으로 레이어를 만들고 싶은 경우..

포샵에 분할영역 나누기라는 기능이 있는데..

![image](https://user-images.githubusercontent.com/5790535/118951526-1e543480-b996-11eb-9f40-4c652aa4756c.png)

이게 웹으로 출력할 때 큰 이미지를 자동으로 포개서 개별 이미지로 만들어주는 기능인데..

![image](https://user-images.githubusercontent.com/5790535/118951599-2f04aa80-b996-11eb-9963-9e29545bfa12.png)

이런 인터페이스가 제공되거든

![image](https://user-images.githubusercontent.com/5790535/118951673-3fb52080-b996-11eb-8351-c437f25d0b61.png)

그럼 이렇게 자동으로 나눠주지..
이런거랑 비슷한 느낌으로 컬러레이어를 만들어주는 기능이 있으면 노가다가 대폭 줄어들것같음

**Comment by redcamel** [comment]
개별이슈로 전환
