### ISSUE TITLE
컬러레이어의 레인지인 경우 두색의 교환

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#74]
![image](https://user-images.githubusercontent.com/5790535/118952027-8e62ba80-b996-11eb-9598-64d226a985a5.png)

레인지의 경우 두 색을 일치시키는 경우가 많아서
좌측을 우측으로 우측을 좌측으로 복사해주는 기능이 있었으면 함

**Comment by redcamel** [comment]
처리완
