### ISSUE TITLE
ui용어통일

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#75]
![image](https://user-images.githubusercontent.com/5790535/118959621-76db0000-b99d-11eb-9ca0-ca14f0837429.png)
캔버스로 하던가 컨테이너로 하던가 하나만 하라능

**Comment by redcamel** [comment]
Container로 통일

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/119071739-55bdf200-ba25-11eb-933d-b5d158627f30.png)
이거 아직 안끝났음
