### ISSUE TITLE
형식이 다른 json을 불렀을떄 방어처리

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGradient#77]
- load처리
- preset load처리

**Comment by hikaMaeng** [comment]
범용 json파싱 후의 밸리데이터를 작성하라능
니가 만들어도 되고 json형식 밸리데이터 라이브러리 찾아보면 꽤 있음.

**Comment by hikaMaeng** [comment]
그외에 귀찮으면 내보낼때 arraybuffer로 바이트화해서 blob으로 출력해버리고 앞에 3바이트정도에 매직 코드 넣어서 확인하던가

**Comment by redcamel** [comment]
적당히 필요한 키값이 있나 없나로 처리
