### ISSUE TITLE
오프셋을 도입하고 싶음

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#79]
![image](https://user-images.githubusercontent.com/5790535/119072249-222f9780-ba26-11eb-95cf-113efbdc27b9.png)
이쯤에 오프셋을 넣고 싶음.
오프셋이란 예를들어 10%를 오프셋으로 설정하면
모든 값이 10%만큼 밀리는 것임

0-50%, 50-100% 이런 컬러레이어가 있는데 오프셋 10%주면
10-60%, 60-110% 로 밀리는 것임.

코닉을 써보면 더 와닿는데 30~50deg에 오프셋 20deg를 주면 알아서 50~70deg로 해석되는거지.

**Comment by redcamel** [comment]
처리완
