### ISSUE TITLE
Add Layer Set변경

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#83]
이 기능을 레이어를 만들 필요없이 기존 레이어에 그라디언트 레이어를 추가하는 기능으로 바뀌어야함

![image](https://user-images.githubusercontent.com/5790535/119297078-33321000-bc95-11eb-9796-523b92379e6c.png)

이자리에 +set 정도로 들어가면 될듯

**Comment by redcamel** [comment]
처리완
