### ISSUE TITLE
visual center scale editor

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#84]
![image](https://user-images.githubusercontent.com/5790535/119297135-56f55600-bc95-11eb-9e6d-b58fcef43105.png)

진호님툴에 반영된 캔버스에서 센터와 스케일을 조정하는 기능을 도입

단 사면 조절점 외에 비율이 유지되는 모서리 조절점추가

각 경계면과 센터선에 스냅되는 기능 추가

**Comment by hikaMaeng** [comment]
생각해보니 조절 박스 외곽 모서리에 회전 핸들도 만들어라

**Comment by redcamel** [comment]
개별이슈로전환
