### ISSUE TITLE
ui짤림

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#86]
![image](https://user-images.githubusercontent.com/5790535/119305616-eefa3c00-bca3-11eb-9763-5f3b469f77bb.png)

**Comment by hikaMaeng** [comment]
![image](https://user-images.githubusercontent.com/5790535/119305707-0df8ce00-bca4-11eb-8350-a034898b2adc.png)

숫자많을때는 스크롤바가 생기도록 만들고 최소 크기를 확보

**Comment by redcamel** [comment]
resolved
