### ISSUE TITLE
set추가시 시작 끝 색 설정

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#87]
![image](https://user-images.githubusercontent.com/5790535/119305795-2d8ff680-bca4-11eb-80c5-4d7c20be8116.png)

별도로 시작색 끝색을 넣을 수 있게 추가
1. 시작색이나 끝색을 바꾸면 다시 색을 재배열
2. 분할수를 바꿔도 재배열
3. 직접 재배열된 색상하나하나를 변경할 수는 있음

**Comment by redcamel** [comment]
resolved
