### ISSUE TITLE
set설정시 시작값만 표시하고 조정가능하게 변경

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#88]
![image](https://user-images.githubusercontent.com/5790535/119305964-6af48400-bca4-11eb-9728-71fc15f8add7.png)

시작에서 끝까지 표시할 필요가 없음
시작값만 표시하고
그걸 조정할 수 있게 하면 됨.
0% |  20%  | 40%

이전 영역은 다음 영역값보다 무조건 작게 유지하게 걸고.

**Comment by hikaMaeng** [comment]
분할수가 많아질때는 생각해보면 게이지를 도입해서 영역을 건드리는 것보다 수치로만 조정하는게 더 좋을거같음.

**Comment by redcamel** [comment]
resolved
