### ISSUE TITLE
어느순간 set 설정시 무한루프로 죽어버림

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#89]
![image](https://user-images.githubusercontent.com/5790535/119306185-c7f03a00-bca4-11eb-8ecd-f229081e387e.png)

음 언제일까..다른창 왔다갔다 하다가 그런거 같은데..암튼 무한루프를 도는지 먹통이 되어버림

**Comment by hikaMaeng** [comment]
어..죽은게 아니었음. 정확하게는 apply를 눌렀을때 먹통이다가
다른 창에 갔다가 다시 오면 반영됨

**Comment by redcamel** [comment]
음이건 division이 겁나많을떄 느려서 그런듯하네요...
루프부분 개선을 하것어요...
그냥 map돌고있는부분만 풀어도 개선될듯

**Comment by redcamel** [comment]
흠 상태업데이트 문제인데 고민좀해볼꼐요

**Comment by redcamel** [comment]
코드하이라이터가 제일 큰문제였고...
제거하고 많이 개선되었으나..
개별 코드 뽑아내는 루프부분도 정리좀 하면 더좋아질듯요

**Comment by redcamel** [comment]
컬러레이어가 많아 짐에 따라
![image](https://user-images.githubusercontent.com/820587/119454111-1ec44500-bd73-11eb-8ec3-7a17deb23106.png)
이걸 그리리는 비용도 증가...
스크롤 위치에 따라.... 적절갯수만 그리는식으로 변경해야함

**Comment by redcamel** [comment]
처리완
