### ISSUE TITLE
퍼센트 픽셀 변환기

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#9]
각 레이어의 색상 위치가 %와 픽셀로 지정할 수 있고
전역에 설정한 캔버스 크기에 따라 상대적으로 그 퍼센트가 몇 픽셀인지 변환해서 처리
캔버스 크기를 바꾸면 자동으로 픽셀값이 갱신

![image](https://user-images.githubusercontent.com/5790535/117416064-f6a3ac00-af53-11eb-8e97-e358017964cb.png)

**Comment by redcamel** [comment]
이거 오묘해요..
그런식으로 첨했다가...
그라데이션 스텝모델은 일단 퍼센테이지로 구현하고 정리

**Comment by hikaMaeng** [comment]
음 하다 못해 픽셀 예상 수치라도 보여주면...안그러면 맨날 계산기 두드려야함

**Comment by redcamel** [comment]
음 이건 원복일단 해보는걸로

**Comment by redcamel** [comment]
#9 로병합
