### ISSUE TITLE
음 버그..

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#93]
![image](https://user-images.githubusercontent.com/5790535/119434308-dd23a200-bd52-11eb-9d3a-46906646f921.png)

레이어 추가하고 프리셋 로드하면서 하나씩 만들어가던 중
먹통이 되면서 완전히 에러가 남
저 까만 원이 더이상 움직이지도 않고 그라데이션이 제대로 되지도 않고..

**Comment by hikaMaeng** [comment]
[RedGradient (3).zip](https://github.com/redcamel/RedGradient/files/6536209/RedGradient.3.zip)

그 당시 세이브 파일

**Comment by hikaMaeng** [comment]
다시 로드하니 첫번째 레이어가 리니어그라데이션 기본값으로 되어있어서 다시 프리셋 로드하고 색상을 왼쪽검정하고
copy L->R했더니 그때부터 죽어버림

**Comment by hikaMaeng** [comment]
음 
![image](https://user-images.githubusercontent.com/5790535/119434509-46a3b080-bd53-11eb-9ed6-23937277c626.png)
다시 해봐도 죽음

**Comment by redcamel** [comment]
기 세이브 파일떄문에
음 기존에 없던 키들이나 이런것들을 없을경우 채워넣도록 하고있는데
올려주신 파일로 확인좀 해볼꼐요

**Comment by redcamel** [comment]
@hikaMaeng 일단 잘못된 컬러값이 들어와서...먹통인건뎅
![image](https://user-images.githubusercontent.com/820587/119439325-1b25c380-bd5d-11eb-9c2b-2ca4ee48f279.png)
진호이랑 상의해보고 처리해야할듯용

**Comment by redcamel** [comment]
처리완
하지만 기존에 저장되버린녀석은 ㅂㅂ
