### ISSUE TITLE
position과 center에 거울반사기능 추가

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#96]
보통
![image](https://user-images.githubusercontent.com/5790535/119604986-f6981d00-be2a-11eb-9b91-d2565a54aa3c.png)
이 아이콘으로 대표되는 거울 반사를 구현했으면 함

50%를 기준으로 23%였으면 50-23 + 50 반대편에 나오게 해주는식으로..
대칭형으로 구현할때가 많다보니 계산기 두드리기 귀찮기도 하고

**Comment by redcamel** [comment]
resolved
