### ISSUE TITLE
before, after 편집기 초안

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#97]
![image](https://user-images.githubusercontent.com/5790535/119683333-86b38200-be7e-11eb-868f-00fd80901dae.png)
이자리쯤에 탭이 생겨서 
main, before, after가 생기고

before나 after는 main의 기능 외에 컨테이너의
![image](https://user-images.githubusercontent.com/5790535/119683444-9df26f80-be7e-11eb-9db3-eec1f82bbe23.png)
이 동네 기능을 포함하여 만들어보면 좋을듯

**Comment by redcamel** [comment]
비포에프터는....보더에도 있어야 된다능

**Comment by redcamel** [comment]
아니지 컨테이너 레벨에

**Comment by hikaMaeng** [comment]
아니..반대라고 비포탭이나 애프터 탭안에 컨테이너에 있던 기능들도 담아야한다고..


2021년 5월 27일 (목) 오전 12:30, Redcamel ***@***.***>님이 작성:

**Comment by redcamel** [comment]
@hikaMaeng #106으로 통합
