### ISSUE TITLE
컨테이너 조절기 기능 추가 수정

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#98]
1
![image](https://user-images.githubusercontent.com/5790535/119783884-a1cad400-bf08-11eb-8597-c2e13f377f2f.png)
position전용 핸들 추가

2
![image](https://user-images.githubusercontent.com/5790535/119783918-aa230f00-bf08-11eb-82dc-cce96c86c555.png)
센터 핸들 빨강계열에서 안보이는거 개선

3
코닉도 회전되니까 회전 핸들 보이게

**Comment by redcamel** [comment]
일단 글러는 가네용...
디자인 개선은 좀있다가 -0-
