### ISSUE TITLE
중앙 원형 영역의 표현에 대해

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGradient#99]
![image](https://user-images.githubusercontent.com/5790535/119784657-641a7b00-bf09-11eb-97ea-84eb7b8a7fbf.png)
이걸 자세히 보면
![image](https://user-images.githubusercontent.com/5790535/119784705-71d00080-bf09-11eb-8b54-28477bb135c2.png)
이게 완전한 원으로 나옴
실제로는 
![image](https://user-images.githubusercontent.com/5790535/119784760-7f858600-bf09-11eb-96dc-d923c6f7dd30.png)
이 비율에 영향을 받아 타원이 되어야함

**Comment by redcamel** [comment]
EndingShape 서클이면 서클로
아닐경우 비율로
